import { z } from 'zod';
import { TetherError } from './errors';

export const MAX_MESSAGE_LENGTH = 2000;

/** Body of POST /api/conversations/:id/messages. `messageId` is generated by the client. */
export const sendMessageRequestSchema = z.object({
  messageId: z.uuid(),
  content: z.string().trim().min(1).max(MAX_MESSAGE_LENGTH),
});
export type SendMessageRequest = z.infer<typeof sendMessageRequestSchema>;

/**
 * A cursor is the highest event `seq` a client has applied; 0 means "nothing yet".
 * Absent means 0. Anything that is not a plain non-negative integer is rejected
 * (no signs, decimals, exponents, whitespace, or unsafe magnitudes).
 */
export function parseCursor(raw: string | undefined): number {
  if (raw === undefined) {
    return 0;
  }
  const cursor = /^\d+$/.test(raw) ? Number(raw) : Number.NaN;
  if (!Number.isSafeInteger(cursor)) {
    throw new TetherError('INVALID_CURSOR', 'Cursor must be a non-negative integer.');
  }
  return cursor;
}

/** The `after` query parameter wins over the standard `Last-Event-ID` header. */
export function resolveCursor(input: {
  after?: string | undefined;
  lastEventId?: string | undefined;
}): number {
  return parseCursor(input.after ?? input.lastEventId);
}
